### ISSUE TITLE
Resizing window breaks label position

### ISSUE THREAD

**Issue by RadarNyan** [ghusse/jQRangeSlider#104]
(1)
Just played a while with all the demo at official site:
http://ghusse.github.io/jQRangeSlider/documentation.html
Then resize the window, play again see how it breaks.

So far as I tested, this only effect on Sliders without step setting.
Setting step: 0.01 or what ever you need will fix this bug.

dataRangeSliders don't have this bug - since they're all "stepped".

(2)
-- BUT, even with step set, there's still bug for Label - try drag a slider on it's range after resizing window. this bug only happens when a slider is "fully slided“ - like this:

$('#rank-range').rangeSlider({
    arrows:false,
    step:1,
    bounds:{min:1, max:50},
    defaultValues:{min:1, max:50}
});

Make a 'legal' move will fix this bug.
not only the ones created like that, manually drag one slider to it's maxium range will cause this bug too.

All the sliders have this bug.

---

Tested on Firefox 20.0.1 / Chromium 28.0.1475.0 (193742)
Windows 8 pro x64 / Windows 7 ultimate x86

**Comment by septychasanah** [comment]
I know that this issue is closed. I'm using newest version (5.7.2) and jQAllRangeSliders-min.js
