### ISSUE TITLE
Incorrect render when container is hidden

### ISSUE THREAD

**Issue by Alchemy86** [ghusse/jQRangeSlider#190]
Hi,

The slider works great but if the container any sliders are in starts off hidden and I then make it show (currently using bootstrap collapse)  the render is weird, the sliders are all smoothed and the range doesn't work.

Can you provide any info on this?

**Comment by ghusse** [comment]
Call the method `resize` after showing the container

http://ghusse.github.io/jQRangeSlider/methods.html#resizeMethod

**Comment by Alchemy86** [comment]
My Hero!
