### ISSUE TITLE
Visual Issues using a date range selector and a scale with just days on it

### ISSUE THREAD

**Issue by sevenatis** [ghusse/jQRangeSlider#196]
I'm using a date range selector and a scale with just days on it. 

1) The days are not centering up on the range sliders. It will cover up the number on the left hand side and the right hand side will show the entire number. 

2) I think this might be a related issue but the final number on the scale is not showing up and the first number appears to be chopped off.
Any guidance on how to fix the issue would be appreciated!

![error](https://cloud.githubusercontent.com/assets/3372086/7776155/d0d6711a-0086-11e5-86ff-928f1025dc5d.png)

**Comment by ghusse** [comment]
1) Set the last bound date to the next day  - 1ms
2) You can adjust number positionning with CSS.
