### ISSUE TITLE
Synchronous rendering for the slider

### ISSUE THREAD

**Issue by ernsheong** [ghusse/jQRangeSlider#213]
Hi there,

The async nature of rendering in the slider seems to be causing issues with unit tests and sometimes in the application, when rendering is taking place consecutively in a short time frame.

Granted tests can be run async, and rendering consecutively is probably bad design (or a code smell) in the first place. But can there be an option to turn off async rendering?

Seems to me like the following code is the source of async rendering:
```
setTimeout($.proxy(this.resize, this), 1);
setTimeout($.proxy(this._initValues, this), 1);
```

Thanks,
Jonathan

**Comment by ghusse** [comment]
Hello,

The slider is rendered asynchronously because it needs to compute its size,
which is not always available after the first call (browsers exposes sizes
of 0 because elements are not visible at the moment the script runs). I did
not have the choice...

**Comment by ernsheong** [comment]
Thanks for the clarification. It might make sense to default to a default size for the first launch, and the recorrect later. Nonetheless this is probably not a priority at the moment, I shall close this for now.
