### ISSUE TITLE
sliders container width not working

### ISSUE THREAD

**Issue by adeel3612** [ghusse/jQRangeSlider#226]
Hello ! I am using this plugin and i must admit that this is a very helpful. I am using this as a slider on my chart and i am getting a problem. Is there anyway i can specify the width of the container. ? 

Let me describe my problem. I am using date range slider. To which i passed an array of the dates. but when the window load the container class `ui-rangeSlider-container` and `ui-rangeSlider-innerBar` appears with the width of only 58. While i want a long range to slide about 680px. 
I have also tried to use the css to do this by specifying the width as !important and it works but then the labels pointers appears at wrong positon. Can you please help me in this regard?

**Comment by ghusse** [comment]
When the slider is created, is the parent hidden and only revealed after an event/timeout/other?

**Comment by adeel3612** [comment]
@ghusse yeah the parent is hidder and created on an event which is fire on a click .

**Comment by adeel3612** [comment]
but the parent is shown through jquery before the slider is created.

**Comment by ghusse** [comment]
Try calling resize after the parent is shown: https://ghusse.github.io/jQRangeSlider/methods.html#resizeMethod

jQRangeSlider needs the parent to be displayed before being created because it needs to compute size relative to the available size (which is 0 when the parent is hidden)

**Comment by adeel3612** [comment]
i am using date range slider.

**Comment by ghusse** [comment]
That's the same: call it using `dateRangeSlider` instead of `rangeSlider`

**Comment by adeel3612** [comment]
@ghusse i have done the same and try to add the resize function where the parent div is updating but still it is the same. I have noticed another thing. when the slider is loaded it have container width 58 but whenever i open the inspect element window in the browser it automatically correct it self.

**Comment by ghusse** [comment]
That is because opening the inspector makes the window resize (and as the
slider registers this event, it calls `resize` on itself).

**Comment by adeel3612** [comment]
i have checked and add it to all the possible outcomes but not working.

**Comment by adeel3612** [comment]
may be the problem is i have a lots of data and the data on which i am including my chart update after some time. So i have added a `timeout` function. 

`setTimeout(function(){
            $('#first_slider').dateRangeSlider('resize');
        }, 650);`
