### ISSUE TITLE
Can we pass our array to the daterangeslide?

### ISSUE THREAD

**Issue by adeel3612** [ghusse/jQRangeSlider#228]
Usually in the `dateRangeSlider` a start and end value is passed and it automatically adjust itself. But i want to pass the dates array of my own because i have duplicate dates also . can i do this in this plugin ?

Any kind of help would be much appreciated

**Comment by ghusse** [comment]
Hello,

I don't know exactly what you're trying to do, but I'm not really sure you
could do it with jQRangeSlider.

**Comment by adeel3612** [comment]
Thank you @ghusse . Cheers!
Just a question i have also created an issue that is it possible i can change the date label? i mean not the dates as a value but only for label. For example I have a date `13-Mar-2017` I want to show only `13-Mar`. This should be applied only on the label because by getting the value i am having a query from the database.

**Comment by adeel3612** [comment]
@ghusse I figure that out by using the formatter we can format the labels !

**Comment by ghusse** [comment]
Hello,

You can use the formatter option, as described in the docs

**Comment by adeel3612** [comment]
@ghusse Thank you i figure that out.
