### ISSUE TITLE
Scales are not being defined properly in date range slider.

### ISSUE THREAD

**Issue by adeel3612** [ghusse/jQRangeSlider#230]
I am using this code  to make my slider. 
```

$(".timescale").dateRangeSlider({
    monthNames: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
            bounds: {min: new Date(self._startDate), max: new Date(self._endDate)},
            defaultValues: {min: new Date(startVal), max: new Date(endVal)},
            formatter: function (val) {
                return getFormattedDate(val,'dd-M');
            },
            scales: [{
                first: function (value) {
                    return value;
                },
                end: function (value) {
                    return value;
                },
                next: function (value) {
                    var next = new Date(value);
                    return new Date(next.setMonth(value.getMonth() + 1));
                },
                label: function (value) {
                    return monthNames[value.getMonth()];
                },
                format: function (tickContainer, tickStart, tickEnd) {
                    tickContainer.addClass("myCustomClass");
                }
            }]
        });
```

Issue is if i start my date other than 1 or 2nd of any month it did not give accurate scale. Like if you have started the dates and bound the dates between `10-Mar-2017` to any other date. scaling for the months start at the wrong place.

![slider](https://user-images.githubusercontent.com/26408294/34222195-8f7fff9a-e5dc-11e7-85a2-fe4c611cd102.png)

As you can see the april is starting where the date is `10-April`. It should be on the `1-April`. It is due to slider starting from `10-Mar`

**Comment by ghusse** [comment]
Can you make sure that your bounds are correctly defined at hour 00:00:00?

**Comment by adeel3612** [comment]
@ghusse sorry i did not understand your comment.

**Comment by adeel3612** [comment]
@ghusse I inspect the bound in the browser and it is defining at 00:00:00.

**Comment by ghusse** [comment]
Can you give me the value of `self._startDate` in your example?

**Comment by adeel3612** [comment]
it is `Sun Mar 12 2017 00:00:00 GMT+0500 (PKT)`

**Comment by ghusse** [comment]
Ok, then your "first" function must return the first day of the (next) month, not the date itself. Otherwise the scale will be shifted of 12 days.

**Comment by adeel3612** [comment]
Thank you @ghusse .How i will put a check in the `first` function to detect the ending of the month and starting of the next month?. Yes currently it is returning the date.

**Comment by ghusse** [comment]
Just construct a new Date object using properties from the parameter : `new Date(date.getFullYear(), date.getMonth(), 1)`

**Comment by adeel3612** [comment]
i have changed the `First` 
```

first: function (value) {
                    return new Date(value.getFullYear(), value.getMonth(), 1);
                },
```

And it worked fine. Can you please tell me what was the problem because i thought the `first` function is for defining the first value.

**Comment by ghusse** [comment]
It defines the first value of the scale, displayed inside the range slider. Min and max values are defined with the `bounds`

**Comment by adeel3612** [comment]
Oh Thank you very much @ghusse for helping me in this matter!. Cheers! :+1:
