### ISSUE TITLE
Loosing labels/handles with JQuery 1.13.0

### ISSUE THREAD

**Issue by claudedeslandes** [ghusse/jQRangeSlider#238]
Bonjour,

    I have been using this module in my project under JQuery UI 1.12.0 / JQuery 3.6.0 with all succes.   
![image](https://user-images.githubusercontent.com/13257529/180576698-f46e1a09-3ba9-4403-b786-901c5e698910.png)

    But now, when testing under JQuery UI 1.13.0 / JQuery 3.6.0, the 'date' label/handle do not display.
![image](https://user-images.githubusercontent.com/13257529/180576812-496b983e-0250-4e3b-ad90-84bf0637c84c.png)

    Any ideas why this happens, ... and what could be the solution ?

    Thank you for this great tool.

    Claude,
   Ontario, Canada

**Comment by ghusse** [comment]
Hello, 

For the moment I don't have time to test and fix the issue. If you have an idea of the reason, I'll be glad to merge the fix.

I'll see if I can take a look at this later this summer, but I cannot promise.

**Comment by claudedeslandes** [comment]
Could I leave you a $ support for you to look at the script ?
write me : claude dot deslandes at gmail.com

**Comment by ghusse** [comment]
This issue is fixed by version 5.8.2 that works correctly with the latest version of jQuery and jQuery UI.
